In [ ]:
import pandas as pd
import numpy as np

In [17]:
matches = pd.read_csv("../data/raw/matches.csv")
deliveries = pd.read_csv("../data/raw/deliveries.csv")

In [18]:
matches_df = matches.copy()
deliveries_df = deliveries.copy()

In [19]:
matches_df.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [20]:
matches_df.tail()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [21]:
matches_df.shape

(756, 18)

In [22]:
deliveries_df.shape

(179078, 21)

In [23]:
matches_df.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='str')

In [24]:
matches_df.columns = matches_df.columns.str.lower()
deliveries_df.columns = deliveries_df.columns.str.lower()

In [25]:
matches_df.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='str')

In [26]:
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   season           756 non-null    str
 2   city             749 non-null    str
 3   date             756 non-null    str
 4   team1            756 non-null    str
 5   team2            756 non-null    str
 6   toss_winner      756 non-null    str
 7   toss_decision    756 non-null    str
 8   result           756 non-null    str
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    str
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    str
 14  venue            756 non-null    str
 15  umpire1          754 non-null    str
 16  umpire2          754 non-null    str
 17  umpire3          119 non-null    str
dtypes: int64(4), str(14)
memory usage: 106.4 KB

In [27]:
matches_df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [28]:
deliveries_df.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [29]:
(matches_df.isnull().sum() / len(matches_df)) * 100

id                  0.000000
season              0.000000
city                0.925926
date                0.000000
team1               0.000000
team2               0.000000
toss_winner         0.000000
toss_decision       0.000000
result              0.000000
dl_applied          0.000000
winner              0.529101
win_by_runs         0.000000
win_by_wickets      0.000000
player_of_match     0.529101
venue               0.000000
umpire1             0.264550
umpire2             0.264550
umpire3            84.259259
dtype: float64

In [30]:
matches_df["city"] = matches_df["city"].fillna("Unknown")

In [31]:
matches_df["winner"] = matches_df["winner"].fillna("No Result")

In [32]:
matches_df["player_of_match"] = matches_df["player_of_match"].fillna("Not Awarded")

In [33]:
matches_df["umpire3"] = matches_df["umpire3"].fillna("Not Available")

In [34]:
matches_df.isnull().sum()

id                 0
season             0
city               0
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             0
win_by_runs        0
win_by_wickets     0
player_of_match    0
venue              0
umpire1            2
umpire2            2
umpire3            0
dtype: int64

In [35]:
matches_df.duplicated().sum()

np.int64(0)

In [36]:
deliveries_df.duplicated().sum()

np.int64(23)

In [37]:
matches_df = matches_df.drop_duplicates()
deliveries_df = deliveries_df.drop_duplicates()

In [38]:
matches_df.dtypes

id                 int64
season               str
city                 str
date                 str
team1                str
team2                str
toss_winner          str
toss_decision        str
result               str
dl_applied         int64
winner               str
win_by_runs        int64
win_by_wickets     int64
player_of_match      str
venue                str
umpire1              str
umpire2              str
umpire3              str
dtype: object

In [40]:
matches_df["date"] = pd.to_datetime(matches_df["date"], dayfirst=True)

In [41]:
matches_df["date"] = pd.to_datetime(matches_df["date"])

In [42]:
matches_df.dtypes

id                          int64
season                        str
city                          str
date               datetime64[us]
team1                         str
team2                         str
toss_winner                   str
toss_decision                 str
result                        str
dl_applied                  int64
winner                        str
win_by_runs                 int64
win_by_wickets              int64
player_of_match               str
venue                         str
umpire1                       str
umpire2                       str
umpire3                       str
dtype: object

In [43]:
matches_df["year"] = matches_df["date"].dt.year
matches_df["month"] = matches_df["date"].dt.month
matches_df["day"] = matches_df["date"].dt.day

In [44]:
matches_df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,...,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,year,month,day
0,1,IPL-2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,Not Available,2017,4,5
1,2,IPL-2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,...,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,Not Available,2017,4,6
2,3,IPL-2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,...,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,Not Available,2017,4,7
3,4,IPL-2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,...,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,Not Available,2017,4,8
4,5,IPL-2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,...,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,Not Available,2017,4,8

In [45]:
matches_df["team1"].unique()

<StringArray>
[        'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',      'Rising Pune Supergiant',
 'Royal Challengers Bangalore',       'Kolkata Knight Riders',
            'Delhi Daredevils',             'Kings XI Punjab',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors',     'Rising Pune Supergiants',
              'Delhi Capitals']
Length: 15, dtype: str

In [46]:
matches_df["team1"].value_counts()

team1
Mumbai Indians                 101
Kings XI Punjab                 91
Chennai Super Kings             89
Royal Challengers Bangalore     85
Kolkata Knight Riders           83
Delhi Daredevils                72
Rajasthan Royals                67
Sunrisers Hyderabad             63
Deccan Chargers                 43
Pune Warriors                   20
Gujarat Lions                   14
Rising Pune Supergiant           8
Kochi Tuskers Kerala             7
Rising Pune Supergiants          7
Delhi Capitals                   6
Name: count, dtype: int64

In [47]:
team_mapping = {
    "Delhi Daredevils": "Delhi Capitals",
    "Rising Pune Supergiant": "Rising Pune Supergiants"
}

In [48]:
team_columns = ["team1", "team2", "winner", "toss_winner"]

for col in team_columns:
    matches_df[col] = matches_df[col].replace(team_mapping)

In [49]:
matches_df.describe()

,id,date,dl_applied,win_by_runs,win_by_wickets,year,month,day
count,756.000000,756,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000
mean,1792.178571,2013-10-07 06:22:51.428571,0.025132,13.283069,3.350529,2013.444444,4.412698,15.726190
min,1.000000,2008-04-18 00:00:00,0.000000,0.000000,0.000000,2008.000000,3.000000,1.000000
25%,189.750000,2011-04-16 00:00:00,0.000000,0.000000,0.000000,2011.000000,4.000000,9.000000
50%,378.500000,2013-05-09 12:00:00,0.000000,0.000000,4.000000,2013.000000,4.000000,16.000000
75%,567.250000,2016-05-18 06:00:00,0.000000,19.000000,6.000000,2016.000000,5.000000,22.000000
max,11415.000000,2019-05-12 00:00:00,1.000000,146.000000,10.000000,2019.000000,6.000000,31.000000
std,3464.478148,NaN,0.156630,23.471144,3.387963,3.366895,0.597166,8.183032

In [50]:
matches_df.to_csv("../data/processed/cleaned_matches.csv", index=False)

deliveries_df.to_csv("../data/processed/cleaned_deliveries.csv", index=False)

In [52]:
teams = pd.read_csv("../data/raw/teams.csv")

In [53]:
teams_df = teams.copy()

In [54]:
teams_df.info()
teams_df.isnull().sum()
teams_df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   team1   15 non-null     str
dtypes: str(1)
memory usage: 252.0 bytes

np.int64(0)

In [55]:
teams_df.to_csv("../data/processed/cleaned_teams.csv", index=False)

In [3]:
import pandas as pd

players = pd.read_excel("../data/raw/Players.xlsx")
players_df = players.copy()

In [4]:
players_df.head()

      Player_Name        DOB Batting_Hand         Bowling_Skill Country
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India
3     A Choudhary        NaT   Right_hand  Left-arm fast-medium     NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN

In [5]:
players_df.shape

(566, 5)

In [6]:
players_df.columns

Index(['Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill', 'Country'], dtype='str')

In [7]:
players_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    566 non-null    str
 1   DOB            471 non-null    datetime64[us]
 2   Batting_Hand   563 non-null    str
 3   Bowling_Skill  502 non-null    str
 4   Country        471 non-null    str
dtypes: datetime64[us](1), str(4)
memory usage: 22.2 KB

In [8]:
players_df.isnull().sum()

Player_Name       0
DOB              95
Batting_Hand      3
Bowling_Skill    64
Country          95
dtype: int64

In [9]:
players_df.duplicated().sum()

np.int64(0)

In [10]:
players_df.to_csv("../data/processed/cleaned_players.csv", index=False)

In [11]:
players_df.head()

      Player_Name        DOB Batting_Hand         Bowling_Skill Country
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India
3     A Choudhary        NaT   Right_hand  Left-arm fast-medium     NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN

In [12]:
players_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    566 non-null    str
 1   DOB            471 non-null    datetime64[us]
 2   Batting_Hand   563 non-null    str
 3   Bowling_Skill  502 non-null    str
 4   Country        471 non-null    str
dtypes: datetime64[us](1), str(4)
memory usage: 22.2 KB

In [13]:
players_df.columns = players_df.columns.str.lower()

In [14]:
players_df.columns = players_df.columns.str.replace(" ", "_")

In [15]:
players_df.columns

Index(['player_name', 'dob', 'batting_hand', 'bowling_skill', 'country'], dtype='str')

In [16]:
players_df.isnull().sum()

player_name       0
dob              95
batting_hand      3
bowling_skill    64
country          95
dtype: int64

In [17]:
players_df["dob"].isnull().sum()

np.int64(95)

In [18]:
players_df["batting_hand"].unique()

<StringArray>
['Right_Hand', 'Right_hand', 'Left_Hand', nan]
Length: 4, dtype: str

In [19]:
players_df["batting_hand"] = players_df["batting_hand"].replace({
    "Right_hand":"Right_Hand",
    "Left_hand":"Left_Hand"
})

In [20]:
players_df["batting_hand"].unique()

<StringArray>
['Right_Hand', 'Left_Hand', nan]
Length: 3, dtype: str

In [21]:
players_df.duplicated().sum()

np.int64(0)

In [22]:
players_df["player_name"].duplicated().sum()

np.int64(0)

In [23]:
players_df.dtypes

player_name                 str
dob              datetime64[us]
batting_hand                str
bowling_skill               str
country                     str
dtype: object

In [24]:
from datetime import datetime

current_year = datetime.now().year

players_df["age"] = current_year - players_df["dob"].dt.year

In [25]:
players_df["age"].describe()

count    471.000000
mean      41.677282
std        5.667929
min       28.000000
25%       37.000000
50%       41.000000
75%       45.000000
max       57.000000
Name: age, dtype: float64

In [26]:
players_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   player_name    566 non-null    str
 1   dob            471 non-null    datetime64[us]
 2   batting_hand   563 non-null    str
 3   bowling_skill  502 non-null    str
 4   country        471 non-null    str
 5   age            471 non-null    float64
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 26.7 KB

In [27]:
players_df.head()

      player_name        dob batting_hand         bowling_skill country   age
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India  35.0
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India  43.0
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India  49.0
3     A Choudhary        NaT   Right_Hand  Left-arm fast-medium     NaN   NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN   NaN

In [28]:
players_df.to_csv("../data/processed/cleaned_players.csv", index=False)

In [29]:
players_df["country"].value_counts()

country
India           264
Australia        72
South Africa     39
New Zealand      22
Sri Lanka        20
West Indies      19
England          14
Pakistan         13
Bangladesh        5
Zimbabwea         2
Netherlands       1
Name: count, dtype: int64

In [30]:
players_df["batting_hand"].value_counts()

batting_hand
Right_Hand    421
Left_Hand     142
Name: count, dtype: int64

In [31]:
players_df["bowling_skill"].value_counts()

bowling_skill
Right-arm medium          107
Right-arm offbreak         91
Right-arm fast-medium      68
Slow left-arm orthodox     50
Right-arm fast             39
Right-arm medium-fast      38
Legbreak                   30
Legbreak googly            28
Left-arm fast-medium       19
Left-arm medium            11
Left-arm medium-fast        9
Slow left-arm chinaman      5
Left-arm fast               4
Right-arm bowler            1
Right-arm Medium            1
Right-arm Fast              1
Name: count, dtype: int64

In [ ]:
import pandas as pd

deliveries = pd.read_csv("../data/processed/cleaned_deliveries.csv")

print(deliveries.shape)

In [1]:
import pandas as pd

teams = pd.read_csv("../data/processed/cleaned_teams.csv")

print(teams.shape)
print(teams.head())

(15, 1)
                   team1
0          Pune Warriors
1  Kolkata Knight Riders
2       Rajasthan Royals
3   Kochi Tuskers Kerala
4          Gujarat Lions